name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: use actions/checkout@v1
        uses: actions/checkout@v1
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: print Date & Time
        run: printf "Current date and time => %s\n" "$(date +'%d.%m.%y - %H:%Mh')"
      - name: Install Dependencies
        run: npm install
      - name: Run a multi-line script
        run:  |
          echo "git status =>"
          git status
          echo
          echo "set =>"
          set
          echo
          echo "ls -la =>"
          ls -la